version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - shopper-network
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: npm run start:prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    networks:
      - shopper-network
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: shopperdb
    networks:
        - shopper-network
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  shopper-network:
    driver: bridge

volumes:
  postgres_data: